# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Dhia\Desktop\joe3.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 480)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.pb1 = QtGui.QProgressBar(self.centralwidget)
        self.pb1.setGeometry(QtCore.QRect(80, 220, 151, 41))
        self.pb1.setMaximum(300)
        self.pb1.setProperty("value", 0)
        self.pb1.setTextVisible(False)
        self.pb1.setObjectName(_fromUtf8("pb1"))
        self.pb2 = QtGui.QProgressBar(self.centralwidget)
        self.pb2.setGeometry(QtCore.QRect(350, 220, 151, 41))
        self.pb2.setMaximum(300)
        self.pb2.setProperty("value", 0)
        self.pb2.setTextVisible(False)
        self.pb2.setObjectName(_fromUtf8("pb2"))
        self.pb3 = QtGui.QProgressBar(self.centralwidget)
        self.pb3.setGeometry(QtCore.QRect(623, 220, 151, 41))
        self.pb3.setMaximum(300)
        self.pb3.setProperty("value", 0)
        self.pb3.setTextVisible(False)
        self.pb3.setObjectName(_fromUtf8("pb3"))
        self.lcd3 = QtGui.QLCDNumber(self.centralwidget)
        self.lcd3.setGeometry(QtCore.QRect(630, 280, 121, 31))
        self.lcd3.setStyleSheet(_fromUtf8(""))
        self.lcd3.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcd3.setMidLineWidth(0)
        self.lcd3.setDigitCount(5)
        self.lcd3.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd3.setProperty("value", 0.0)
        self.lcd3.setObjectName(_fromUtf8("lcd3"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 80, 101, 81))
        self.pushButton.setStyleSheet(_fromUtf8(""))
        self.pushButton.setText(_fromUtf8(""))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(670, 80, 101, 81))
        self.pushButton_2.setStyleSheet(_fromUtf8(""))
        self.pushButton_2.setText(_fromUtf8(""))
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.lcd1 = QtGui.QLCDNumber(self.centralwidget)
        self.lcd1.setGeometry(QtCore.QRect(100, 280, 121, 31))
        self.lcd1.setStyleSheet(_fromUtf8(""))
        self.lcd1.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcd1.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd1.setProperty("value", 0.0)
        self.lcd1.setObjectName(_fromUtf8("lcd1"))
        self.lcd2 = QtGui.QLCDNumber(self.centralwidget)
        self.lcd2.setGeometry(QtCore.QRect(360, 280, 121, 31))
        self.lcd2.setStyleSheet(_fromUtf8(""))
        self.lcd2.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcd2.setLineWidth(3)
        self.lcd2.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd2.setProperty("value", 0.0)
        self.lcd2.setObjectName(_fromUtf8("lcd2"))
        self.pb4 = QtGui.QProgressBar(self.centralwidget)
        self.pb4.setGeometry(QtCore.QRect(85, 353, 151, 41))
        self.pb4.setMaximum(300)
        self.pb4.setProperty("value", 0)
        self.pb4.setTextVisible(False)
        self.pb4.setObjectName(_fromUtf8("pb4"))
        self.pb5 = QtGui.QProgressBar(self.centralwidget)
        self.pb5.setGeometry(QtCore.QRect(350, 352, 151, 41))
        self.pb5.setProperty("value", 0)
        self.pb5.setTextVisible(False)
        self.pb5.setObjectName(_fromUtf8("pb5"))
        self.pb6 = QtGui.QProgressBar(self.centralwidget)
        self.pb6.setGeometry(QtCore.QRect(623, 351, 151, 41))
        self.pb6.setMaximum(300)
        self.pb6.setProperty("value", 0)
        self.pb6.setTextVisible(False)
        self.pb6.setObjectName(_fromUtf8("pb6"))
        self.lcd6 = QtGui.QLCDNumber(self.centralwidget)
        self.lcd6.setGeometry(QtCore.QRect(640, 410, 121, 31))
        self.lcd6.setStyleSheet(_fromUtf8(""))
        self.lcd6.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcd6.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd6.setProperty("value", 0.0)
        self.lcd6.setObjectName(_fromUtf8("lcd6"))
        self.lcd5 = QtGui.QLCDNumber(self.centralwidget)
        self.lcd5.setGeometry(QtCore.QRect(360, 410, 121, 31))
        self.lcd5.setStyleSheet(_fromUtf8(""))
        self.lcd5.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcd5.setFrameShadow(QtGui.QFrame.Raised)
        self.lcd5.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd5.setProperty("value", 0.0)
        self.lcd5.setObjectName(_fromUtf8("lcd5"))
        self.lcd4 = QtGui.QLCDNumber(self.centralwidget)
        self.lcd4.setGeometry(QtCore.QRect(100, 410, 121, 31))
        self.lcd4.setStyleSheet(_fromUtf8(""))
        self.lcd4.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcd4.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd4.setProperty("value", 0.0)
        self.lcd4.setObjectName(_fromUtf8("lcd4"))
        self.checkBox = QtGui.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(40, 285, 16, 17))
        self.checkBox.setText(_fromUtf8(""))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.checkBox_2 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(300, 285, 16, 17))
        self.checkBox_2.setText(_fromUtf8(""))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.checkBox_3 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(570, 285, 16, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_3.sizePolicy().hasHeightForWidth())
        self.checkBox_3.setSizePolicy(sizePolicy)
        self.checkBox_3.setText(_fromUtf8(""))
        self.checkBox_3.setIconSize(QtCore.QSize(30, 30))
        self.checkBox_3.setShortcut(_fromUtf8(""))
        self.checkBox_3.setChecked(False)
        self.checkBox_3.setAutoRepeat(False)
        self.checkBox_3.setTristate(False)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.checkBox_4 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(30, 420, 16, 17))
        self.checkBox_4.setText(_fromUtf8(""))
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.checkBox_5 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(300, 420, 16, 17))
        self.checkBox_5.setText(_fromUtf8(""))
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.checkBox_6 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_6.setGeometry(QtCore.QRect(570, 420, 16, 17))
        self.checkBox_6.setText(_fromUtf8(""))
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 480))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("GUI1.jpg")))
        self.label.setScaledContents(True)
        self.label.setWordWrap(False)
        self.label.setObjectName(_fromUtf8("label"))
        self.dialC = QtGui.QDial(self.centralwidget)
        self.dialC.setGeometry(QtCore.QRect(195, 18, 151, 151))
        self.dialC.setMaximum(50)
        self.dialC.setObjectName(_fromUtf8("dialC"))
        self.Cons = QtGui.QLCDNumber(self.centralwidget)
        self.Cons.setGeometry(QtCore.QRect(370, 90, 141, 61))
        self.Cons.setFrameShape(QtGui.QFrame.NoFrame)
        self.Cons.setFrameShadow(QtGui.QFrame.Raised)
        self.Cons.setLineWidth(2)
        self.Cons.setObjectName(_fromUtf8("Cons"))
        self.UPcheck = QtGui.QCheckBox(self.centralwidget)
        self.UPcheck.setGeometry(QtCore.QRect(564, 51, 16, 21))
        self.UPcheck.setAutoFillBackground(False)
        self.UPcheck.setStyleSheet(_fromUtf8(""))
        self.UPcheck.setText(_fromUtf8(""))
        self.UPcheck.setTristate(False)
        self.UPcheck.setObjectName(_fromUtf8("UPcheck"))
        self.DOWNcheck = QtGui.QCheckBox(self.centralwidget)
        self.DOWNcheck.setGeometry(QtCore.QRect(564, 113, 16, 21))
        self.DOWNcheck.setAutoFillBackground(False)
        self.DOWNcheck.setStyleSheet(_fromUtf8(""))
        self.DOWNcheck.setText(_fromUtf8(""))
        self.DOWNcheck.setTristate(False)
        self.DOWNcheck.setObjectName(_fromUtf8("DOWNcheck"))
        self.label.raise_()
        self.pb1.raise_()
        self.pb2.raise_()
        self.pb3.raise_()
        self.lcd3.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.lcd1.raise_()
        self.lcd2.raise_()
        self.pb4.raise_()
        self.pb5.raise_()
        self.pb6.raise_()
        self.lcd6.raise_()
        self.lcd5.raise_()
        self.lcd4.raise_()
        self.checkBox.raise_()
        self.checkBox_2.raise_()
        self.checkBox_3.raise_()
        self.checkBox_4.raise_()
        self.checkBox_5.raise_()
        self.checkBox_6.raise_()
        self.dialC.raise_()
        self.Cons.raise_()
        self.UPcheck.raise_()
        self.DOWNcheck.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.dialC, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.Cons.display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))

