# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Dhia\Desktop\ui1\joe2.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 480)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.pb1 = QtGui.QProgressBar(self.centralwidget)
        self.pb1.setGeometry(QtCore.QRect(120, 180, 118, 23))
        self.pb1.setProperty("value", 24)
        self.pb1.setTextVisible(True)
        self.pb1.setObjectName(_fromUtf8("pb1"))
        self.pb2 = QtGui.QProgressBar(self.centralwidget)
        self.pb2.setGeometry(QtCore.QRect(350, 180, 118, 23))
        self.pb2.setProperty("value", 24)
        self.pb2.setTextVisible(True)
        self.pb2.setObjectName(_fromUtf8("pb2"))
        self.pb3 = QtGui.QProgressBar(self.centralwidget)
        self.pb3.setGeometry(QtCore.QRect(560, 180, 118, 23))
        self.pb3.setProperty("value", 24)
        self.pb3.setTextVisible(True)
        self.pb3.setObjectName(_fromUtf8("pb3"))
        self.lcd3 = QtGui.QLCDNumber(self.centralwidget)
        self.lcd3.setGeometry(QtCore.QRect(580, 220, 64, 23))
        self.lcd3.setStyleSheet(_fromUtf8("background-color :rgb(255, 255, 127)"))
        self.lcd3.setProperty("value", 1.2)
        self.lcd3.setObjectName(_fromUtf8("lcd3"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(60, 30, 131, 71))
        self.pushButton.setStyleSheet(_fromUtf8("background-color :rgb(0, 170, 0)"))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(610, 30, 131, 71))
        self.pushButton_2.setStyleSheet(_fromUtf8("background-color :rgb(255, 0, 0)"))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(180, 380, 151, 41))
        self.pushButton_3.setStyleSheet(_fromUtf8("background-color :rgb(85, 255, 255)"))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(440, 380, 151, 41))
        self.pushButton_4.setStyleSheet(_fromUtf8("background-color :rgb(85, 255, 255)"))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.lcd1 = QtGui.QLCDNumber(self.centralwidget)
        self.lcd1.setGeometry(QtCore.QRect(140, 220, 64, 23))
        self.lcd1.setStyleSheet(_fromUtf8("background-color :rgb(255, 255, 127)"))
        self.lcd1.setProperty("value", 1.2)
        self.lcd1.setObjectName(_fromUtf8("lcd1"))
        self.lcd2 = QtGui.QLCDNumber(self.centralwidget)
        self.lcd2.setGeometry(QtCore.QRect(370, 220, 64, 23))
        self.lcd2.setStyleSheet(_fromUtf8("background-color :rgb(255, 255, 127)"))
        self.lcd2.setProperty("value", 1.2)
        self.lcd2.setObjectName(_fromUtf8("lcd2"))
        self.pb4 = QtGui.QProgressBar(self.centralwidget)
        self.pb4.setGeometry(QtCore.QRect(120, 280, 118, 23))
        self.pb4.setProperty("value", 24)
        self.pb4.setObjectName(_fromUtf8("pb4"))
        self.pb5 = QtGui.QProgressBar(self.centralwidget)
        self.pb5.setGeometry(QtCore.QRect(350, 280, 118, 23))
        self.pb5.setProperty("value", 24)
        self.pb5.setObjectName(_fromUtf8("pb5"))
        self.pb6 = QtGui.QProgressBar(self.centralwidget)
        self.pb6.setGeometry(QtCore.QRect(560, 280, 118, 23))
        self.pb6.setProperty("value", 24)
        self.pb6.setObjectName(_fromUtf8("pb6"))
        self.lcd6 = QtGui.QLCDNumber(self.centralwidget)
        self.lcd6.setGeometry(QtCore.QRect(580, 320, 64, 23))
        self.lcd6.setStyleSheet(_fromUtf8("background-color :rgb(255, 255, 127)"))
        self.lcd6.setProperty("value", 1.2)
        self.lcd6.setObjectName(_fromUtf8("lcd6"))
        self.lcd5 = QtGui.QLCDNumber(self.centralwidget)
        self.lcd5.setGeometry(QtCore.QRect(370, 320, 64, 23))
        self.lcd5.setStyleSheet(_fromUtf8("background-color :rgb(255, 255, 127)"))
        self.lcd5.setProperty("value", 1.2)
        self.lcd5.setObjectName(_fromUtf8("lcd5"))
        self.lcd4 = QtGui.QLCDNumber(self.centralwidget)
        self.lcd4.setGeometry(QtCore.QRect(140, 320, 64, 23))
        self.lcd4.setStyleSheet(_fromUtf8("background-color :rgb(255, 255, 127)"))
        self.lcd4.setProperty("value", 1.2)
        self.lcd4.setObjectName(_fromUtf8("lcd4"))
        self.checkBox = QtGui.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(90, 180, 70, 17))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.checkBox_2 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(320, 180, 70, 17))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.checkBox_3 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(530, 180, 70, 17))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.checkBox_4 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(90, 280, 70, 17))
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.checkBox_5 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_5.setGeometry(QtCore.QRect(320, 280, 70, 17))
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.checkBox_6 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_6.setGeometry(QtCore.QRect(530, 280, 70, 17))
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 800, 480))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("18624427_10209362356768081_1878227934_n.jpg")))
        self.label.setScaledContents(True)
        self.label.setWordWrap(False)
        self.label.setObjectName(_fromUtf8("label"))
        self.label.raise_()
        self.pb1.raise_()
        self.pb2.raise_()
        self.pb3.raise_()
        self.lcd3.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.lcd1.raise_()
        self.lcd2.raise_()
        self.pb4.raise_()
        self.pb5.raise_()
        self.pb6.raise_()
        self.lcd6.raise_()
        self.lcd5.raise_()
        self.lcd4.raise_()
        self.checkBox.raise_()
        self.checkBox_2.raise_()
        self.checkBox_3.raise_()
        self.checkBox_4.raise_()
        self.checkBox_5.raise_()
        self.checkBox_6.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.pushButton.setText(_translate("MainWindow", "START", None))
        self.pushButton_2.setText(_translate("MainWindow", "STOP", None))
        self.pushButton_3.setText(_translate("MainWindow", "UP", None))
        self.pushButton_4.setText(_translate("MainWindow", "DOWN", None))
        self.checkBox.setText(_translate("MainWindow", "1", None))
        self.checkBox_2.setText(_translate("MainWindow", "2", None))
        self.checkBox_3.setText(_translate("MainWindow", "3", None))
        self.checkBox_4.setText(_translate("MainWindow", "4", None))
        self.checkBox_5.setText(_translate("MainWindow", "5", None))
        self.checkBox_6.setText(_translate("MainWindow", "6", None))

